//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLC_Rohaan.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResultOfArrayOfBrandTypeIM_P2MBHX", Namespace="http://schemas.datacontract.org/2004/07/UserManagementSystem.Service")]
    [System.SerializableAttribute()]
    public partial class ResponseResultOfArrayOfBrandTypeIM_P2MBHX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserManagementSystem.Entities.BrandType[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLC_Rohaan.Service.ResponseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementSystem.Entities.BrandType[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLC_Rohaan.Service.ResponseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/UserManagementSystem.Service")]
    public enum ResponseStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResultOfArrayOfCityIM_P2MBHX", Namespace="http://schemas.datacontract.org/2004/07/UserManagementSystem.Service")]
    [System.SerializableAttribute()]
    public partial class ResponseResultOfArrayOfCityIM_P2MBHX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserManagementSystem.Entities.City[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLC_Rohaan.Service.ResponseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementSystem.Entities.City[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLC_Rohaan.Service.ResponseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResultOfArrayOfCountryIM_P2MBHX", Namespace="http://schemas.datacontract.org/2004/07/UserManagementSystem.Service")]
    [System.SerializableAttribute()]
    public partial class ResponseResultOfArrayOfCountryIM_P2MBHX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserManagementSystem.Entities.Country[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLC_Rohaan.Service.ResponseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementSystem.Entities.Country[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLC_Rohaan.Service.ResponseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResultOfArrayOfEmailTypeIM_P2MBHX", Namespace="http://schemas.datacontract.org/2004/07/UserManagementSystem.Service")]
    [System.SerializableAttribute()]
    public partial class ResponseResultOfArrayOfEmailTypeIM_P2MBHX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserManagementSystem.Entities.EmailType[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLC_Rohaan.Service.ResponseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementSystem.Entities.EmailType[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLC_Rohaan.Service.ResponseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResultOfArrayOfPhoneTypeIM_P2MBHX", Namespace="http://schemas.datacontract.org/2004/07/UserManagementSystem.Service")]
    [System.SerializableAttribute()]
    public partial class ResponseResultOfArrayOfPhoneTypeIM_P2MBHX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserManagementSystem.Entities.PhoneType[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLC_Rohaan.Service.ResponseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementSystem.Entities.PhoneType[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLC_Rohaan.Service.ResponseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResultOfArrayOfStateIM_P2MBHX", Namespace="http://schemas.datacontract.org/2004/07/UserManagementSystem.Service")]
    [System.SerializableAttribute()]
    public partial class ResponseResultOfArrayOfStateIM_P2MBHX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserManagementSystem.Entities.State[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLC_Rohaan.Service.ResponseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementSystem.Entities.State[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLC_Rohaan.Service.ResponseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResultOfArrayOfPublicationIM_P2MBHX", Namespace="http://schemas.datacontract.org/2004/07/UserManagementSystem.Service")]
    [System.SerializableAttribute()]
    public partial class ResponseResultOfArrayOfPublicationIM_P2MBHX : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserManagementSystem.Entities.Publication[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLC_Rohaan.Service.ResponseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserManagementSystem.Entities.Publication[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLC_Rohaan.Service.ResponseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseResultOfboolean", Namespace="http://schemas.datacontract.org/2004/07/UserManagementSystem.Service")]
    [System.SerializableAttribute()]
    public partial class ResponseResultOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SLC_Rohaan.Service.ResponseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SLC_Rohaan.Service.ResponseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IUmsService")]
    public interface IUmsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetBrands", ReplyAction="http://tempuri.org/IUmsService/GetBrandsResponse")]
        SLC_Rohaan.Service.ResponseResultOfArrayOfBrandTypeIM_P2MBHX GetBrands();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetBrands", ReplyAction="http://tempuri.org/IUmsService/GetBrandsResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfBrandTypeIM_P2MBHX> GetBrandsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetCities", ReplyAction="http://tempuri.org/IUmsService/GetCitiesResponse")]
        SLC_Rohaan.Service.ResponseResultOfArrayOfCityIM_P2MBHX GetCities(int stateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetCities", ReplyAction="http://tempuri.org/IUmsService/GetCitiesResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfCityIM_P2MBHX> GetCitiesAsync(int stateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetCountries", ReplyAction="http://tempuri.org/IUmsService/GetCountriesResponse")]
        SLC_Rohaan.Service.ResponseResultOfArrayOfCountryIM_P2MBHX GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetCountries", ReplyAction="http://tempuri.org/IUmsService/GetCountriesResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfCountryIM_P2MBHX> GetCountriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetEmailTypes", ReplyAction="http://tempuri.org/IUmsService/GetEmailTypesResponse")]
        SLC_Rohaan.Service.ResponseResultOfArrayOfEmailTypeIM_P2MBHX GetEmailTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetEmailTypes", ReplyAction="http://tempuri.org/IUmsService/GetEmailTypesResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfEmailTypeIM_P2MBHX> GetEmailTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetPhoneTypes", ReplyAction="http://tempuri.org/IUmsService/GetPhoneTypesResponse")]
        SLC_Rohaan.Service.ResponseResultOfArrayOfPhoneTypeIM_P2MBHX GetPhoneTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetPhoneTypes", ReplyAction="http://tempuri.org/IUmsService/GetPhoneTypesResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfPhoneTypeIM_P2MBHX> GetPhoneTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetStates", ReplyAction="http://tempuri.org/IUmsService/GetStatesResponse")]
        SLC_Rohaan.Service.ResponseResultOfArrayOfStateIM_P2MBHX GetStates(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetStates", ReplyAction="http://tempuri.org/IUmsService/GetStatesResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfStateIM_P2MBHX> GetStatesAsync(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetUserBooks", ReplyAction="http://tempuri.org/IUmsService/GetUserBooksResponse")]
        SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX GetUserBooks(int userId, bool IsAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetUserBooks", ReplyAction="http://tempuri.org/IUmsService/GetUserBooksResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX> GetUserBooksAsync(int userId, bool IsAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetUserBooksByBrand", ReplyAction="http://tempuri.org/IUmsService/GetUserBooksByBrandResponse")]
        SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX GetUserBooksByBrand(UserManagementSystem.Entities.BrandType brandType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetUserBooksByBrand", ReplyAction="http://tempuri.org/IUmsService/GetUserBooksByBrandResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX> GetUserBooksByBrandAsync(UserManagementSystem.Entities.BrandType brandType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetUserBooksByBrandId", ReplyAction="http://tempuri.org/IUmsService/GetUserBooksByBrandIdResponse")]
        SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX GetUserBooksByBrandId(int brandTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/GetUserBooksByBrandId", ReplyAction="http://tempuri.org/IUmsService/GetUserBooksByBrandIdResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX> GetUserBooksByBrandIdAsync(int brandTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/SetLeads", ReplyAction="http://tempuri.org/IUmsService/SetLeadsResponse")]
        SLC_Rohaan.Service.ResponseResultOfboolean SetLeads(System.Guid userId, bool leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/SetLeads", ReplyAction="http://tempuri.org/IUmsService/SetLeadsResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfboolean> SetLeadsAsync(System.Guid userId, bool leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/SetNotification", ReplyAction="http://tempuri.org/IUmsService/SetNotificationResponse")]
        SLC_Rohaan.Service.ResponseResultOfboolean SetNotification(System.Guid userId, bool notifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUmsService/SetNotification", ReplyAction="http://tempuri.org/IUmsService/SetNotificationResponse")]
        System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfboolean> SetNotificationAsync(System.Guid userId, bool notifications);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUmsServiceChannel : SLC_Rohaan.Service.IUmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UmsServiceClient : System.ServiceModel.ClientBase<SLC_Rohaan.Service.IUmsService>, SLC_Rohaan.Service.IUmsService {
        
        public UmsServiceClient() {
        }
        
        public UmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SLC_Rohaan.Service.ResponseResultOfArrayOfBrandTypeIM_P2MBHX GetBrands() {
            return base.Channel.GetBrands();
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfBrandTypeIM_P2MBHX> GetBrandsAsync() {
            return base.Channel.GetBrandsAsync();
        }
        
        public SLC_Rohaan.Service.ResponseResultOfArrayOfCityIM_P2MBHX GetCities(int stateId) {
            return base.Channel.GetCities(stateId);
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfCityIM_P2MBHX> GetCitiesAsync(int stateId) {
            return base.Channel.GetCitiesAsync(stateId);
        }
        
        public SLC_Rohaan.Service.ResponseResultOfArrayOfCountryIM_P2MBHX GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfCountryIM_P2MBHX> GetCountriesAsync() {
            return base.Channel.GetCountriesAsync();
        }
        
        public SLC_Rohaan.Service.ResponseResultOfArrayOfEmailTypeIM_P2MBHX GetEmailTypes() {
            return base.Channel.GetEmailTypes();
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfEmailTypeIM_P2MBHX> GetEmailTypesAsync() {
            return base.Channel.GetEmailTypesAsync();
        }
        
        public SLC_Rohaan.Service.ResponseResultOfArrayOfPhoneTypeIM_P2MBHX GetPhoneTypes() {
            return base.Channel.GetPhoneTypes();
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfPhoneTypeIM_P2MBHX> GetPhoneTypesAsync() {
            return base.Channel.GetPhoneTypesAsync();
        }
        
        public SLC_Rohaan.Service.ResponseResultOfArrayOfStateIM_P2MBHX GetStates(int countryId) {
            return base.Channel.GetStates(countryId);
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfStateIM_P2MBHX> GetStatesAsync(int countryId) {
            return base.Channel.GetStatesAsync(countryId);
        }
        
        public SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX GetUserBooks(int userId, bool IsAdmin) {
            return base.Channel.GetUserBooks(userId, IsAdmin);
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX> GetUserBooksAsync(int userId, bool IsAdmin) {
            return base.Channel.GetUserBooksAsync(userId, IsAdmin);
        }
        
        public SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX GetUserBooksByBrand(UserManagementSystem.Entities.BrandType brandType) {
            return base.Channel.GetUserBooksByBrand(brandType);
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX> GetUserBooksByBrandAsync(UserManagementSystem.Entities.BrandType brandType) {
            return base.Channel.GetUserBooksByBrandAsync(brandType);
        }
        
        public SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX GetUserBooksByBrandId(int brandTypeId) {
            return base.Channel.GetUserBooksByBrandId(brandTypeId);
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfArrayOfPublicationIM_P2MBHX> GetUserBooksByBrandIdAsync(int brandTypeId) {
            return base.Channel.GetUserBooksByBrandIdAsync(brandTypeId);
        }
        
        public SLC_Rohaan.Service.ResponseResultOfboolean SetLeads(System.Guid userId, bool leads) {
            return base.Channel.SetLeads(userId, leads);
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfboolean> SetLeadsAsync(System.Guid userId, bool leads) {
            return base.Channel.SetLeadsAsync(userId, leads);
        }
        
        public SLC_Rohaan.Service.ResponseResultOfboolean SetNotification(System.Guid userId, bool notifications) {
            return base.Channel.SetNotification(userId, notifications);
        }
        
        public System.Threading.Tasks.Task<SLC_Rohaan.Service.ResponseResultOfboolean> SetNotificationAsync(System.Guid userId, bool notifications) {
            return base.Channel.SetNotificationAsync(userId, notifications);
        }
    }
}
